services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5148:5148'
    environment:
      - 'PORT=${PORT}'
      - 'ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}'
      - 'DATABASE_CONNECTION_STRING=${DATABASE_CONNECTION_STRING}'
    volumes:
      - './src:/app/src'
    networks:
      - coolify

networks:
  coolify:
    external: true

